version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/ci-cd-test
permissions:
  - object: /home/ubuntu/moduform/ci-cd-test
    owner: ubuntu
    group: ubuntu
hooks:
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 60
      runas: ubuntu
