# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask
        sudo python3 app.py
    - name: Upload to AWS
      env:
        AWS_HOST: ${{ secrets.AWS_HOST }}
        AWS_USERNAME: ${{ secrets.AWS_USERNAME }}
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      run: |
        echo "$PRIVATE_KEY" > aws-private-key.pem
        chmod 600 aws-private-key.pem
        scp -o StrictHostKeyChecking=no -i aws-private-key.pem -r . $AWS_USERNAME@$AWS_HOST:/home/ubuntu/ci-cd-test
        ssh -o StrictHostKeyChecking=no -i aws-private-key.pem $AWS_USERNAME@$AWS_HOST "cd /home/ubuntu/ci-cd-test && python3 app.py"
      shell: bash
